python ../train/train.py \
    --tiny \
    --dataset ../data/coco2voc2tfrecord/coco2017_train.tfrecord \
    --val_dataset ../data/coco2voc2tfrecord/coco2017_val.tfrecord \
    --classes ../data/coco.names \
    --num_classes 80 \
    --mode fit \
    --transfer frozen \
    --batch_size 32 \
    --epochs 100 \
    --weights ../checkpoints/yolov3-tiny.tf \
    --weights_num_classes 80
